swagger: '2.0'
info:
  title: Dendrite Morphology Classification API
  version: "0.1"
  description: An API that can classify dendrite type, spiny vs Aspiny 

paths:
  /health:
    get:
      summary: Checks the health of the service
      description: Returns the health status of the service
      operationId: dendrite_classification_api.health
      responses:
        '200':
          description: Service is healthy
        '500':
          description: Service is unhealthy

  /predict:
    post:
      summary: Entrypoint to our prediction function
      operationId: dendrite_classification_api.predict
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
        - in: formData
          name: upstroke_downstroke_ratio_short_square
          required: true
          description: upstroke downstroke ratio response to short square stim
          type: number
        - in: formData
          name: peak_v_ramp
          required: true
          description: peak voltage 
          type: number
        - in: formData
          name: average_interspike_interval
          required: true
          description: average interspike interval
          type: number
      responses:
        '200':
          description: Classification performed successfully
        '500':
          description: Unable to perform the classification
